sudo: required
services:
  - docker
langauge: generic

before_install:
  - docker build -t jibolaolu/docker-seanny -f Dockerfile.dev .

script:
  - docker run jibolaolu/docker-seanny npm run test -- --coverage
  
